export interface Contact {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  avatar: string;
  role: string;
  status: 'online' | 'offline' | 'busy';
}

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Sarah Connor',
    email: 'sarah.connor@cyberdyne.com',
    phone: '+1 (555) 019-2831',
    address: '1432 Tech Way, Los Angeles, CA 90025',
    avatar: 'https://i.pravatar.cc/100?img=1',
    role: 'Operations Lead',
    status: 'online',
  },
  {
    id: '2',
    name: 'Marcus Wright',
    email: 'mwright@projectangel.org',
    phone: '+1 (555) 014-9821',
    address: '88 Cyber Court, San Francisco, CA 94107',
    avatar: 'https://i.pravatar.cc/100?img=2',
    role: 'Principal Systems Architect',
    status: 'busy',
  },
  {
    id: '3',
    name: 'Elena Rostova',
    email: 'elena.rostova@techcorp.io',
    phone: '+44 20 7946 0912',
    address: '42 Baker St, London, NW1 6XE, UK',
    avatar: 'https://i.pravatar.cc/100?img=5',
    role: 'Lead UX Architect',
    status: 'online',
  },
  {
    id: '4',
    name: 'John Doe',
    email: 'john.doe@innovate.co',
    phone: '+1 (555) 012-3456',
    address: '500 Innovation Way, Austin, TX 78701',
    avatar: 'https://i.pravatar.cc/100?img=11',
    role: 'Senior Product Manager',
    status: 'offline',
  },
  {
    id: '5',
    name: 'Aisha Rahman',
    email: 'aisha.r@globalops.net',
    phone: '+971 4 368 0000',
    address: 'Sheikh Zayed Rd, Dubai, UAE',
    avatar: 'https://i.pravatar.cc/100?img=9',
    role: 'Director of Marketing',
    status: 'online',
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'dkim@nextgen.kr',
    phone: '+82 2 1234 5678',
    address: 'Teheran-ro 521, Seoul, South Korea',
    avatar: 'https://i.pravatar.cc/100?img=8',
    role: 'Mobile Team Lead',
    status: 'busy',
  },
  {
    id: '7',
    name: 'Sofia Martinez',
    email: 'sofia.m@creativedesign.co',
    phone: '+34 91 372 8492',
    address: 'Gran Via 45, Madrid, 28013, Spain',
    avatar: 'https://i.pravatar.cc/100?img=16',
    role: 'Senior Visual Designer',
    status: 'online',
  },
  {
    id: '8',
    name: 'Alexander Neumann',
    email: 'a.neumann@cloudbase.de',
    phone: '+49 89 2424 0',
    address: 'Leopoldstraße 23, Munich, 80802, Germany',
    avatar: 'https://i.pravatar.cc/100?img=12',
    role: 'Infrastructure Architect',
    status: 'offline',
  },
  {
    id: '9',
    name: 'Jane Smith',
    email: 'jane.smith@solutions.net',
    phone: '+1 (555) 987-6543',
    address: '128 Business Rd, Seattle, WA 98101',
    avatar: 'https://i.pravatar.cc/100?img=21',
    role: 'Customer Success Specialist',
    status: 'online',
  },
  {
    id: '10',
    name: 'Liam O\'Connor',
    email: 'l.oconnor@codelab.ie',
    phone: '+353 1 496 0123',
    address: '22 Silicon Dock, Dublin 2, Ireland',
    avatar: 'https://i.pravatar.cc/100?img=15',
    role: 'Backend Staff Engineer',
    status: 'busy',
  },
  {
    id: '11',
    name: 'Yuki Tanaka',
    email: 'y.tanaka@quantumtech.jp',
    phone: '+81 3 5555 0199',
    address: 'Shibuya 2-chome, Tokyo, Japan',
    avatar: 'https://i.pravatar.cc/100?img=28',
    role: 'Research Scientist',
    status: 'online',
  },
  {
    id: '12',
    name: 'Chloe Laurent',
    email: 'chloe.l@luxecreative.fr',
    phone: '+33 1 42 27 78 90',
    address: 'Champs-Élysées 102, Paris, 75008, France',
    avatar: 'https://i.pravatar.cc/100?img=29',
    role: 'Creative Director',
    status: 'offline',
  },
  {
    id: '13',
    name: 'Vikram Singh',
    email: 'vikram.s@indiatech.in',
    phone: '+91 80 4123 4567',
    address: 'Outer Ring Rd, Bangalore, 560103, India',
    avatar: 'https://i.pravatar.cc/100?img=33',
    role: 'Lead Data Engineer',
    status: 'online',
  },
  {
    id: '14',
    name: 'Isabella Rossi',
    email: 'i.rossi@designstudio.it',
    phone: '+39 02 8765 4321',
    address: 'Via Tortona 35, Milan, 20144, Italy',
    avatar: 'https://i.pravatar.cc/100?img=34',
    role: 'Brand Manager',
    status: 'busy',
  },
  {
    id: '15',
    name: 'Tariq Al-Mansoor',
    email: 't.almansoor@qatarpets.qa',
    phone: '+974 4400 1234',
    address: 'West Bay, Doha, Qatar',
    avatar: 'https://i.pravatar.cc/100?img=37',
    role: 'HR Business Partner',
    status: 'online',
  },
  {
    id: '16',
    name: 'Emily Watson',
    email: 'emily.w@edutech.edu',
    phone: '+61 2 9385 1000',
    address: 'Anzac Parade, Sydney, NSW 2052, Australia',
    avatar: 'https://i.pravatar.cc/100?img=40',
    role: 'Instructional Designer',
    status: 'offline',
  },
  {
    id: '17',
    name: 'Gabriel Silva',
    email: 'gsilva@devstudio.com.br',
    phone: '+55 11 3060 9000',
    address: 'Av. Paulista 1000, São Paulo, SP, Brazil',
    avatar: 'https://i.pravatar.cc/100?img=43',
    role: 'iOS Engineer',
    status: 'online',
  },
  {
    id: '18',
    name: 'Natasha Romanoff',
    email: 'natasha.r@shield-ops.net',
    phone: '+1 (555) 098-1122',
    address: 'Secret Headquarters, Washington, DC 20001',
    avatar: 'https://i.pravatar.cc/100?img=44',
    role: 'Security Analyst',
    status: 'busy',
  },
  {
    id: '19',
    name: 'Peter Parker',
    email: 'p.parker@dailybugle.com',
    phone: '+1 (555) 345-6789',
    address: '20 Ingram St, Forest Hills, NY 11375',
    avatar: 'https://i.pravatar.cc/100?img=52',
    role: 'Freelance Photographer',
    status: 'online',
  },
  {
    id: '20',
    name: 'Bruce Wayne',
    email: 'bwayne@wayneenterprises.com',
    phone: '+1 (555) 777-8888',
    address: 'Wayne Manor, Gotham City, NJ 07001',
    avatar: 'https://i.pravatar.cc/100?img=59',
    role: 'Managing Director',
    status: 'offline',
  },
  {
    id: '21',
    name: 'Clark Kent',
    email: 'ckent@dailyplanet.com',
    phone: '+1 (555) 123-9999',
    address: '344 Clinton St, Metropolis, IL 62960',
    avatar: 'https://i.pravatar.cc/100?img=60',
    role: 'Senior Reporter',
    status: 'online',
  },
  {
    id: '22',
    name: 'Diana Prince',
    email: 'diana.prince@museum.org',
    phone: '+1 (555) 999-0000',
    address: '1000 Gateway Rd, Washington, DC 20006',
    avatar: 'https://i.pravatar.cc/100?img=61',
    role: 'Antiquities Curator',
    status: 'busy',
  },
  {
    id: '23',
    name: 'Barry Allen',
    email: 'ballen@ccpd.gov',
    phone: '+1 (555) 287-4678',
    address: 'Central City Police Dept, Central City, MO 64015',
    avatar: 'https://i.pravatar.cc/100?img=62',
    role: 'Forensic Chemist',
    status: 'online',
  },
  {
    id: '24',
    name: 'Arthur Curry',
    email: 'acurry@lighthouse.org',
    phone: '+1 (555) 902-1200',
    address: 'Amnesty Bay Lighthouse, Maine 04001',
    avatar: 'https://i.pravatar.cc/100?img=63',
    role: 'Maritime Specialist',
    status: 'offline',
  },
  {
    id: '25',
    name: 'Victor Stone',
    email: 'vstone@cybernetics.org',
    phone: '+1 (555) 606-2020',
    address: 'S.T.A.R. Labs, Detroit, MI 48201',
    avatar: 'https://i.pravatar.cc/100?img=64',
    role: 'Systems Engineer',
    status: 'online',
  },
];
